<a href="https://colab.research.google.com/github/jurados/NotesPytorch/blob/main/%5B01%5D_PyTorch_Basis_and_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
print('PyTorch version:', torch.__version__)

PyTorch version: 2.3.1+cu121


The next code show us the GPU features

In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Introduction to Tensor

PyTorch tensors are created using `torch.Tensor()`

In [4]:
# Create a scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Dimension of a scalar
scalar.ndim

0

In [6]:
# Get tensor back as Python number
scalar.item()

7

In [8]:
# Create tensor
x = torch.tensor(3.)
x, x.ndim

(tensor(3.), 0)

What makes `PyTorch` special is we can automatically compute the derivate of `y`, the tensors that have `requires_grad` set to `True`(id est). To compute the derivates, we can call the `.backward` method on our results `y`.

In [9]:
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(3., requires_grad=True)
w, b

(tensor(4., requires_grad=True), tensor(3., requires_grad=True))

$$ y = w \times x + b$$

In [10]:
# Arithmetic operations
y = w*x+b
y

tensor(15., grad_fn=<AddBackward0>)

In [11]:
# Compute derivates
y.backward()

The derivates of `y`, the input tensors are stored in the `.grad` property of the respective tensors.

Thus, the analytical derivatives are using the corresponding values $x = 7$, $w = 4$ and $b = 3$:

$$\partial_x y = w = 4$$
$$\partial_w y = x = 7$$
$$\partial_b y = 1 $$

But we did not select the `requires_grad=True` respect to $x$ variable, then $\partial_x y = 0$.

In [12]:
# Display gradients
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [13]:
# Create a Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [16]:
# Create a Matrix
matrix = torch.tensor([[7,8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
matrix.ndim

2

In [18]:
matrix.shape

torch.Size([2, 2])

In [19]:
# Select an element from the matrix
matrix[1]

tensor([ 9, 10])

In [20]:
# Create a Tensor
tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
tensor.ndim

3

In [22]:
tensor.shape

torch.Size([1, 3, 3])

In [23]:
# Select an element from the Tensor
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

## Random Tensors

In [24]:
# Create a random tensors of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6338, 0.5967, 0.1817, 0.7951],
        [0.9492, 0.0434, 0.6145, 0.4355],
        [0.3755, 0.6698, 0.8976, 0.7175]])

In [25]:
random_tensor.ndim

2

In [26]:
# Create a random tensor like image dimensions
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and Ones

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [30]:
# Use torch.range()
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor DataTypes

Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning.

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right service

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, #Datatype is the tensor (e.g. float32 or float16)
                               device=None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
# Float 32 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])

## Getting information from tensors

Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning.

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get a shape from a ternsonr, can use `tensor.shape`
3. Tensors not on the right service - to get device from a tensor, can use `tensor.device`

In [38]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3684, 0.9344, 0.1534, 0.9191],
        [0.0568, 0.0512, 0.8193, 0.0722],
        [0.1652, 0.5135, 0.5953, 0.8171]])

In [39]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [40]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3684, 0.9344, 0.1534, 0.9191],
        [0.0568, 0.0512, 0.8193, 0.0722],
        [0.1652, 0.5135, 0.5953, 0.8171]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [41]:
# Create a tensor
tensor = torch.tensor([1,2,3])

In [43]:
print(tensor + 10) # Addition
print(tensor * 10) # Multiplication
print(tensor - 10) # Substraction

# Try out PyTorch in-built functions
print()
print(torch.mul(tensor,10))
print(torch.add(tensor,10))

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])

tensor([10, 20, 30])
tensor([11, 12, 13])


## Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [44]:
# Element wise multiplication
tensor = torch.tensor([1,2,3])

print(tensor, '*', tensor)
print(f'Equals: {tensor * tensor}')
print(f'Equals: {torch.mul(tensor,tensor)}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
Equals: tensor([1, 4, 9])


In [45]:
# Matrix multiplication
print(tensor, 'dot', tensor)
torch.matmul(tensor, tensor)

tensor([1, 2, 3]) dot tensor([1, 2, 3])


tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 2.54 ms, sys: 0 ns, total: 2.54 ms
Wall time: 6.9 ms


tensor(14)

In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.13 ms, sys: 0 ns, total: 1.13 ms
Wall time: 1.08 ms


tensor(14)

## Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. THe **inner dimension** must match:
  - `(3,2) @ (3,2)` wont work
  - `(2,3) @ (3,2)` will work
  - `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimension**
  - `(2,3) @ (3,2) -> (2,2)`
  - `(3,2) @ (2,3) -> (3,3)`

In [49]:
# Correct way to multiplied matrix
torch.matmul(torch.rand(3,2), torch.rand(3,2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [50]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.3644, 0.6215],
        [0.9505, 1.1714]])

### One of the most common errors in deep learning: shape errors

In [51]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [52]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensor using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [53]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [54]:
# The matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} same shape as above, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) same shape as above, tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc. (tensor aggregation)

In [55]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [56]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [57]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [58]:
# Find the mean
# Nothe: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [59]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [60]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [61]:
# Find the position in tensor that has the minimum value with argmin()
# argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [62]:
x[0]

tensor(1)

In [63]:
# Find the position in tensor that has the minimum value with argmax()
# argmmax() -> returns index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

In [64]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - returns a view of an input tensor of certain shape but keep the same memory as the original tensor.
- Stacking - combines multiple tensors on top of each other (vstack) or side-by-side (hstack).
- Squeeze - removes all `1` dimensions from a tensor.
- Unsqueeze - adds a `1`dimension to a target tensor.
- Permute - return a view of the input with dimensions permuted (swapped) in a certain way.

In [66]:
# Let's create a tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [67]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [68]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [69]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [70]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0) # dim=0 -> stack vertically, dim=1 -> stack horizontally
print('Stacked with dim = 0 : \n', x_stacked)
x_stacked = torch.stack([x,x,x,x], dim = 1)
print('Stacked with dim = 1 : \n', x_stacked)

Stacked with dim = 0 : 
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Stacked with dim = 1 : 
 tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [71]:
# torch.squeeze() - removes all singles dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [72]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f'Previous tensor: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # dim=0 -> zero dimention position, dim=1 -> first dimention position
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [73]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0 , 1) # Shifts axis 0->1, 1->2, 2->0

print(f'Previuos shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [color_channels, height, width]

Previuos shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [74]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting  data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [75]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
#Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [78]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [79]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [80]:
# Get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [81]:
# Get all values of the 0th dimension but only the 1 index values of the 1st and 2nd dimensions
x[:,1,1]

tensor([5])

In [82]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

- Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [83]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
# warning: when converting from numpy -> pytorch, pytorch reflects numpy's default
# datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [84]:
array.dtype

dtype('float64')

In [85]:
# Change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [86]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [87]:
numpy_tensor.dtype

dtype('float32')

In [88]:
# Change the tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`star with a random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seeds**.

Essentially with the random seeds does is "flavour" the randomness.

In [89]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1821, 0.1385, 0.4131, 0.0830],
        [0.9117, 0.6804, 0.7520, 0.9063],
        [0.5938, 0.4980, 0.1728, 0.8363]])
tensor([[0.3445, 0.6118, 0.0396, 0.3559],
        [0.9904, 0.8921, 0.0479, 0.9190],
        [0.9235, 0.9180, 0.7838, 0.0994]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [90]:
# Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED) # Only works for one random tensor
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster comptations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### Getting a GPU

1. Easiest - Use Google Colab for a free GPU.
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's a lot of options.
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

In [ ]:
!nvidia-smi

### Check for GPU access with PyTorch

In [91]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

False

In [92]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [93]:
# Count number of devices
torch.cuda.device_count()

0

## Putting tensors (and models) on the GPUs

The reasons we want our tensors/models on the GPUs is because using a GPU results in faster computations.

In [94]:
# Create a tensor (default on the GPU)
tensor = torch.tensor([1,2,3], device = 'cpu')

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [95]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

## Moving tensors back to the CPU

In [96]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [97]:
# To fix the GPU tensor with NumPy issue, we can first set it to the GPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [98]:
tensor_on_gpu

tensor([1, 2, 3])